name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          cd ./docs-gen
          yarn install --frozen-lockfile
      - name: Build website
        run: |
          cd ./docs-gen
          yarn run deploy
        env:
          GIT_USER: marc0l92