on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Check that the last commit is not tagged
        run: |
          echo test
